version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.test
    env_file:
      - ./environments/testing.env
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    env_file:
      - ./environments/testing.env
    ports:
      - "8000:8000"

  mongodb:
    image: mongo:6.0
    volumes:
      - mongodb_test_data:/data/db

volumes:
  mongodb_test_data:
