version: '3.8'

services:
  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - frontend_build:/app/build
      - ssl_certs:/etc/ssl/private

  backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile.prod
    restart: always
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - backend_data:/app/data
      - media_files:/app/media

  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ssl_certs:/etc/ssl/private
      - frontend_build:/usr/share/nginx/html
      - media_files:/usr/share/nginx/media
    depends_on:
      - frontend
      - backend

volumes:
  frontend_build:
  backend_data:
  mongodb_data:
  media_files:
  ssl_certs:
